import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: " To-Do App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased bg-[#F0F4F3]`}
      >
        <div className="absolute top-0 left-0">
          <Image
            src="/shape.svg"
            alt="top left icon"
            width={200}
            height={170}
          />
        </div>
        {children}
      </body>
    </html>
  );
}
